# Generated by Django 4.1.3 on 2023-01-11 15:32

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_advertisements_apps_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='text',
            field=ckeditor.fields.RichTextField(default='Текст'),
        ),
    ]
