# Generated by Django 4.1.3 on 2023-01-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_advertisements_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisements',
            old_name='text',
            new_name='apps_text',
        ),
    ]
